version: '3'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"

  mongodb:
    expose:
      - "27017"

  mongo-express:
    ports:
      - "8081:8081"
    expose:
      - "8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb

  redis:
    expose:
      - "6379"

  redis-commander:
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8082:8081"